name: Ejemplo CI/CD #nombre del pipeline

on: [push] #disparador

jobs: #importante seguir la identación pues indica que es un paso
    inicio: #puede ser cualquier nombre como conexion, conectar github a jenkins
        runs-on: windows-latest
        #Pasos:
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo"
            - name: Instalar Checkout
              uses: actions/checkout@v4    
    build:
        runs-on: windows-latest
        needs: [inicio]
        steps:
            - name: mostrar texto
              run: echo "Construir"
            - name: Instalar PHP y COMPOSER
              run: |
                choco install php --version=8.1
                choco install composer
                php -v
                composer --version  
            - name: Instalar MySql
              run: |
                choco install mysql --version=8.0.27
                Start-Service mysql
                mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED with mysql_native_password BY 'root';"mysql -u root -proot -e "CREATE DATABASE test;"
    test:
        runs-on: windows-latest
        needs: [build]
        steps:
            - name: mostrar texto
              run: echo "Test"

    deploy:
        runs-on: windows-latest
        needs: [test]
        steps:
            - name: mostrar texto
              run: echo "Deploy"              