name: Ejemplo CI/CD #nombre del pipeline

on: [push] #disparador

jobs: #importante seguir la identación pues indica que es un paso
    inicio: #puede ser cualquier nombre como conexion, conectar github a jenkins
        runs-on: windows-latest
        #Pasos:
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo"
            - name: Instalar Checkout
              uses: actions/checkout@v4    
    build:
        runs-on: windows-latest
        needs: [inicio]
        steps:
            - name: mostrar texto
              run: echo "Construir"

    test:
        runs-on: windows-latest
        needs: [build]
        steps:
            - name: mostrar texto
              run: echo "Test"

    deploy:
        runs-on: windows-latest
        needs: [test]
        steps:
            - name: mostrar texto
              run: echo "Deploy"              