name: Ejemplo CI/CD

on: [push]

jobs:
    inicio:
        runs-on: windows-latest
        #Pasos a seguir:
        steps:
            - name: mostrar texto
              run: echo "Hola mundo"

        build:
            runs-on: windows-latest
            needs: [inicio]
                - name: texto
                  run: echo "construir"

        test:
            runs-on: windows-latest
            needs: [build]
                - name: texto
                  run: echo "test"    
         deploy:
            runs-on: windows-latest
            needs: [test]
                - name: texto
                  run: echo "deploy"                